version: '3'
name: web_weather

volumes:
  postgres_data:

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --reload --port 8000"
    env_file: ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
